artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion ## under artifacts folder it will create another folder data_ingestion 
  #source_url: https://github.com/NeerajAI/AzureFundamentals/blob/master/ClusesDateset.zip
  source_url: https://github.com/NeerajAI/AzureFundamentals/raw/refs/heads/master/ClusesDateset.zip
  local_data_file: artifacts/data_ingestion/data.zip 
  unzip_dir: artifacts/data_ingestion